spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mytrophy_db
#    username: root
#    password: 1234

    url: jdbc:mysql://3.37.122.106:3306/mytrophy
    username: root
    password: mytrophy
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 1076652919726-clghs8nj9nc6oq0461i9ii4iv90op41h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://mytrophy.site/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email
          naver:
            client-name: naver
            client-id: M__lwomWP26ogS9cROiz
            client-secret: KeeYEbPqoz
            redirect-uri: http://3.37.122.106:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    servlet:
      multipart:
        enabled: true           # 멀티파트 요청 활성화
        max-file-size: 10MB     # 업로드 파일의 최대 크기
        max-request-size: 10MB  # 전체 요청의 최대 크기

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
steam:
  api-key: E747BF736400A81DFDF11557E236014E


softawii:
  steam:
    token: F927DD1980502AE9F832129551700D42

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

server:
  tomcat:
    mbeanregistry:
      enabled: true

#logging:
#  level:
#    root: DEBUG

clova:
  api:
    url: "https://clovastudio.apigw.ntruss.com/testapp/v1/api-tools/embedding/clir-emb-dolphin/2d99acdc264b42028346ee146ccb54a8"
    key: "NTA0MjU2MWZlZTcxNDJiY7Tc7YqpiO5S8ZK3UrW5bdFB6gfdB0U0qxpT0u1+hU5y"
    gateway:
      key: "g2SFTEXXqVScW007z4mOTr46g3PBYFKy3Q8p021h"
    request:
      id: "812b32c6-2eb6-4657-8c2c-c762f40f50b7"